### ISSUE TITLE
Стенограмма

### ISSUE THREAD

**Issue by RedFoxCub** [RedFoxCub/maybe#2]
Прослушать запись и сравнить ее с набраной стенограммой. Пропущенный текст выделить # Красным цветом. Текст лишний - # Синим. Текст, который звучит иначе - # Зеленым.
Желательно до завтрашнего дня.

**Comment by Refenz** [comment]
@RedFoxCub 
Done.
The file has been sent to e-mail.
P.S. Only red was used for all cases

Please check and close the issue if all is done.
